services:
  aliconcon-client-customer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    container_name: aliconcon-client-customer
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3007}:3000"
    environment:
      - PORT=3000
